[tool.poetry]
name = "davidkhala.purview"
version = "0.1.0"
description = ""
authors = ["David Liu <david-khala@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
azure-identity = "^1.19.0"
azure-purview-catalog = "^1.0.0b4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
