on:
  workflow_dispatch:
  push:


jobs:
  test:
    environment: kyndryl
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      TENANT_ID: ${{vars.TENANT_ID}}
      CLIENT_ID: ${{vars.CLIENT_ID}}
    steps:
    - uses: actions/checkout@main
    - uses: davidkhala/poetry-buildpack@main
      with:
        working-directory: purview/py
        test-entry-point: pytest
        tests: purview/py/tests
  publish:
    runs-on: windows-latest
        
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          working-directory: purview/py
      - run: poetry run build
        working-directory: purview/py
      - run: ./tests/test.ps1
        working-directory: purview/py
        env:
          DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
          DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          TENANT_ID: ${{vars.TENANT_ID}}
          CLIENT_ID: ${{vars.CLIENT_ID}}
      - uses: softprops/action-gh-release@master
        with:
          files: |
            purview/py/dist/cli.exe
          