on:
  workflow_dispatch:
  push:


jobs:
  test:
    environment: david-khala@hotmail.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: davidkhala/uv-buildpack@main
      with:
        working-directory: purview/py
        test-entry-point: pytest
        tests: purview/py/tests
        version: 3.12
      env:
        DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
        CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        TENANT_ID: ${{vars.TENANT_ID}}
        CLIENT_ID: ${{vars.CLIENT_ID}}
  publish:
    runs-on: windows-latest
    environment: david-khala@hotmail.com
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: purview/py
          version: 3.12
      - run: uv run build
        shell: bash
        working-directory: purview/py
      - run: ./tests/test.ps1
        working-directory: purview/py
        env:
          DATABRICKS_HOST: ${{vars.DATABRICKS_HOST}}
          DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          TENANT_ID: ${{vars.TENANT_ID}}
          CLIENT_ID: ${{vars.CLIENT_ID}}
      - uses: softprops/action-gh-release@master
        with:
          tag_name: purview
          files: |
            purview/py/dist/purview.exe
          